# Site settings
title: WCAG ACT RULES CG
description: >
  Accessibility conformance testing rules for HTML.
baseurl: ""
sass:
    sass_dir: assets/css
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 2..3
collections:
  rules:
    output: true
  drafts:
    output: true
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: rules
    values:
      name: undefined
      layout: rule
  - scope:
      path: ""
      type: drafts
    values:
      layout: rule
      draft: true
      name: undefined
      test_mode: undefined
  - scope:
      path: "pages/glossary"
      type: pages
    values:
      layout: glossary
      category: glossary
exclude:
- _testcases-embeds
- _drafts/early-stage
- _drafts/outdated
- _rules/outdated