# Site settings
title: Auto-WCAG Rules
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/auto-wcag"
url: "http://auto-wcag/github.io/"

markdown: kramdown
# Use github markdown
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 2..3

collections:
  rules:
    output: true
  rule-tests:
    output: true
  drafts:
    output: true
  draft-tests:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: rules
    values:
      layout: rule
  - scope:
      path: ""
      type: drafts
    values:
      layout: rule
      draft: true
      name: undefined
      rule_id: undefined
      test_mode: undefined
  - scope:
      path: ""
      type: rule-tests
    values:
      layout: testcase
  - scope:
      path: ""
      type: draft-tests
    values:
      layout: testcase
      draft: true
  - scope:
      path: pages/algorithms
    values:
      category: algorithms

exclude:
- _drafts/early-stage
- _draft-testcase-embeds