version: 2

general:
  branches:
    only:
     - develop

defaults: &defaults
  docker:
    - image: circleci/node:10-browsers

restore_dependency_cache: &restore_dependency_cache
  restore_cache:
    keys:
      - v3-npm-cache-{{ checksum "package.json" }}
      - v3-npm-cache-

jobs:
  # A dummy placeholder job to not fail circleci status for other branches than `master`
  base: 
    <<: *defaults
    steps: 
      - run: echo "circleci job to not fail status checks"
  # get deps
  dependencies:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: v1-npm-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  deploy:
    <<: *defaults
    steps:
      - checkout
      - <<: *restore_dependency_cache
      - run: npm run build
      - deploy:
          name: Deploy to master branch from develop branch
          command: bash .circleci/publish-site.sh
            
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - base
      - dependencies:
          filters:
            branches:
              only: develop
      - deploy:
          requires:
            - dependencies
          filters:
            branches:
              only: develop