name: Dispatch build request

# Run on push/commit targetting `develop` branch
on:
  push:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - shell: bash
      name: send 'repository_dispatch' trigger to ACT W repository
      run: |
        curl -XPOST 
          -u "${{ secrets.USER_NAME }}:${{ secrets.USER_PAT }}" 
          -H "Accept: application/vnd.github.everest-preview+json"  
          -H "Content-Type: application/json" https://api.github.com/repos/act-rules/act-rules-web/dispatches 
          --data '{ "event_type": "build_application" }'